CREATE TABLE USERS (
    USER_ID INT AUTOINCREMENT PRIMARY KEY,
    NAME VARCHAR,
    EMAIL VARCHAR UNIQUE,
    PASSWORD VARCHAR
);

CREATE TABLE DESTINATION (
    DESTINATION_ID INT AUTOINCREMENT PRIMARY KEY,
    CITY VARCHAR,
    MEAL_COST FLOAT,
    ACCOMODATION_COST FLOAT,
    TRANSPORT_COST FLOAT
);

CREATE TABLE COST_PREDICTIONS (
    PREDICTION_ID INT AUTOINCREMENT PRIMARY KEY,
    USER_ID INT,
    DESTINATION_ID INT,
    MEAL_COST FLOAT,
    ACCOMODATION_COST FLOAT,
    TRANSPORT_COST FLOAT,
    TOTAL_COST FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
